
```{r include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(message=FALSE)
```

```{r call-library}
library(data.table)
library(ggplot2)
library(feather)
library(grid)
library(gridExtra)
library(ngram)
#library(qdap)
library(foreign)
#library(xlsx)
library(foreach)
library(scales)
library(survival)
library(ggfortify)
library(ggpubr)

```


```{r meta-data}
# By default, the working directory for R code chunks is the directory that contains the Rmd document
# that is like to root directory of a website

# Build relative path to subfolders data
filepath_new <- file.path("Data", "New")
filepath_old <- file.path("Data", "Old")

# Read meta data in Old folder
if (file.exists(file.path(filepath_old, "META.feather"))) {
  # if file META exists read it
  meta_old <- data.table(read_feather(file.path(filepath_old, "META.feather")))
  OldV <- paste("Old,",max(meta_old$fu_close_dmy))
} else {
  # if not read tblCENTER instead
  meta_old <- data.table(read_feather(file.path(filepath_old, "tblCENTER.feather")))
  OldV <- paste("Old,",max(meta_old$close_d))
}

if (file.exists(file.path(filepath_new, "META.feather"))) {
  # if file META exists read it
  meta_new <- data.table(read_feather(file.path(filepath_new, "META.feather")))
  NewV <- paste("New,",max(meta_new$fu_close_dmy))
  # build report title
  title_var <- paste("Data consistency check for", meta_new$cohort[1], max(meta_new$fu_close_dmy))
} else {
  # if not read tblCENTER instead
  meta_new <- data.table(read_feather(file.path(filepath_new, "tblCENTER.feather")))
  NewV <- paste("New,",max(meta_new$close_d))
  # build report title
  title_var <- paste("Data consistency check for", meta_new$program[1], max(meta_new$close_d))
}

# CHDAO   18.01.2021 Add variables to use in report header below
# title_var (above) and today
today <- format(Sys.Date(), "%B %d %Y")

rm(meta_old)
rm(meta_new)

```
---
title: `r title_var`
author: Yann Ruffieux
date: `r today`
output: html_document
---
Blue== New version ; red == Old version

## CD4
```{r CD4}

if (file.exists(file.path(filepath_old, "LAB.feather"))) {
  DATAlab1 <- data.table(read_feather(file.path(filepath_old, "LAB.feather")))
  #DATAcd4A1 <- DATAlab1[lab_id %in% c("CD4A","CD4P"),]
  DATAcd4A1 <- DATAlab1[lab_id=="CD4A",] # Separate CD4A (cell count)
  DATAcd4A1[,year:=year(lab_dmy)]
  
  DATAcd4P1 <- DATAlab1[lab_id=="CD4P",] # ... and CD4P (%)
  DATAcd4P1[,year:=year(lab_dmy)]
} else {
  DATAcd41 <- data.table(read_feather(file.path(filepath_old, "tblLAB_CD4.feather")))
  DATAcd4A1 <- DATAcd41[cd4_u==1] # Take CD4 cell count
  DATAcd4A1[,year:=year(cd4_d)]    
  
  DATAcd4P1 <- DATAcd41[cd4_u==2] # Take CD4% 
  DATAcd4P1[,year:=year(cd4_d)]   
}  
DATAcd4A1[,V:=OldV]
DATAcd4P1[,V:=OldV]
  
if (file.exists(file.path(filepath_new, "LAB.feather"))) {
  # if file LAB exists (old DB structure) then read it
  DDATAlab2 <- data.table(read_feather(file.path(filepath_new, "LAB.feather")))
  # DATAcd4A2<- DATAlab2[lab_id %in% c("CD4A","CD4P"),]
  DATAcd4A2<- DATAlab2[lab_id=="CD4A",] # Separate CD4A (cell count)
  DATAcd4A2[,year:=year(lab_dmy)]
  
  DATAcd4P2<- DATAlab2[lab_id=="CD4P",] # ... and CD4P (%)
  DATAcd4P2[,year:=year(lab_dmy)]
} else {
  # if not, try to read tblLAB_CD4 instead
  DATAcd42<- data.table(read_feather(file.path(filepath_new, "tblLAB_CD4.feather")))
  DATAcd4A2<- DATAcd42[cd4_u==1] # Take only CD4% 
  DATAcd4A2[,year:=year(cd4_d)]   
  
  DATAcd4P2 <- DATAcd42[cd4_u==2] # Take CD4% 
  DATAcd4P2[,year:=year(cd4_d)]  
}
DATAcd4A2[,V:=NewV]
DATAcd4P2[,V:=NewV]

# bind 2 data frames by row (append) then plot CD4 cell count per year
DATAcd4A <- rbind(DATAcd4A1[,.(V,year)],DATAcd4A2[,.(V,year)])

DATAgcd4A <- data.table(table(DATAcd4A$year,DATAcd4A$V))

DATAgcd4A$V2 <- as.factor(DATAgcd4A$V2)
DATAgcd4A$V2 <- factor(DATAgcd4A$V2, levels(DATAgcd4A$V2)[c(2,1)])

DATAgcd4A <- DATAgcd4A[V1 %between% c(2004,2020),]

ggplot(DATAgcd4A, aes(x=V1, y=N, fill=V2)) +
  geom_bar(stat="identity", color="black", position=position_dodge(),width = .7)+
  theme_minimal()+   ylab("Count") + xlab("") + ggtitle("CD4 cell count by year")+
  theme(plot.title = element_text(hjust = 0.5,size=14,face="bold"))+theme(legend.title = element_blank())+
  theme(legend.position="bottom")

# 01.02.2021 CHDAO Added
# bind 2 data frames by row (append) then plot CD4 percent per year
DATAcd4P <- rbind(DATAcd4P1[,.(V,year)],DATAcd4P2[,.(V,year)])

DATAgcd4P <- data.table(table(DATAcd4P$year,DATAcd4P$V))

DATAgcd4P$V2 <- as.factor(DATAgcd4P$V2)
DATAgcd4P$V2 <- factor(DATAgcd4P$V2, levels(DATAgcd4P$V2)[c(2,1)])

DATAgcd4P <- DATAgcd4P[V1 %between% c(2004,2020),]

ggplot(DATAgcd4P, aes(x=V1, y=N, fill=V2)) +
  geom_bar(stat="identity", color="black", position=position_dodge(),width = .7)+
  theme_minimal()+   ylab("Count") + xlab("") + ggtitle("CD4 percent by year")+
  theme(plot.title = element_text(hjust = 0.5,size=14,face="bold"))+theme(legend.title = element_blank())+
  theme(legend.position="bottom") 

rm(DATAcd4A1)
rm(DATAcd4A2)
rm(DATAcd4A)
rm(DATAgcd4A)

rm(DATAcd4P1)
rm(DATAcd4P2)
rm(DATAcd4P)
rm(DATAgcd4P)
```

## RNA

```{r RNA}
# Plot RNA lab test per year and per day
# Read viral load lab tests

# if data is read from LAB (old DB structure) then extract the "RNA" lab tests only
if (exists("DATAlab1")) {
  DATARNA1 <- DATAlab1[lab_id=="RNA",]
  DATARNA1[,year:=year(lab_dmy)]
} else {
  # if not, read tblLAB_RNA instead
  DATARNA1 <- data.table(read_feather(file.path(filepath_old, "tblLAB_RNA.feather")))
  DATARNA1[,year:=year(rna_d)]
}
DATARNA1[,V:=OldV]

# if data is read from LAB (old DB structure) then extract the "RNA" lab tests only
if (exists("DATAlab2")) {
  DATARNA2 <- DATAlab2[lab_id=="RNA",]
  DATARNA2[,year:=year(lab_dmy)]
} else {
  # if not, read tblLAB_RNA (new DB structure)
  DATARNA2 <- data.table(read_feather(file.path(filepath_new, "tblLAB_RNA.feather")))
  DATARNA2[,year:=year(rna_d)]
}
DATARNA2[,V:=NewV]

# Append (row bind) 2 data tables
DATARNA <- rbind(DATARNA1[,.(V,year)],DATARNA2[,.(V,year)])
# Aggregrate table, grouped by $year and $V
DATAgrna <- data.table(table(DATARNA$year,DATARNA$V))

DATAgrna <- rbind(DATAgrna,data.table(V1=2000,V2=OldV,N=0))

DATAgrna$V2 <- as.factor(DATAgrna$V2)
DATAgrna$V2 <- factor(DATAgrna$V2, levels(DATAgrna$V2)[c(2,1)])
DATAgrna <- DATAgrna[V1 %between% c(2012,2020),]

# Plot per year
ggplot(DATAgrna, aes(x=V1, y=N, fill=V2)) +
        geom_bar(stat="identity", color="black", position=position_dodge(),width = .7)+
        theme_minimal()+   ylab("Count") + xlab("") + ggtitle("RNA by year")+
        theme(plot.title = element_text(hjust = 0.5,size=14,face="bold"))+theme(legend.title = element_blank())+
        theme(legend.position="bottom")

#################RNA
# CHDAO 20.01.2021 DROPPED
# DATARNA1 <- DATAlab1[lab_id=="RNA",]
# DATARNA2 <- DATAlab2[lab_id=="RNA",]
# DATARNA1[,V:=OldV]
# DATARNA2[,V:=NewV]

# Simply replace year by date
if ("lab_dmy" %in% colnames(DATARNA1)) {
  DATARNA1[,year:=as.Date(lab_dmy)]
} else {
  DATARNA1[,year:=as.Date(rna_d)]
}  

if ("lab_dmy" %in% colnames(DATARNA2)) {
  DATARNA2[,year:=as.Date(lab_dmy)]
} else {
  DATARNA2[,year:=as.Date(rna_d)]
}

DATARNA <- rbind(DATARNA1[,.(V,year)],DATARNA2[,.(V,year)])
DATARNA <- DATARNA[year(year)>=2012,]

DATAgrna <- data.table(table(DATARNA$year,DATARNA$V))
DATAgrna[,V1:=as.Date(V1)]
DATAgrna[V2==OldV,N:=-N]

DATAgrna$V2 <- as.factor(DATAgrna$V2)
DATAgrna$V2 <- factor(DATAgrna$V2, levels(DATAgrna$V2)[c(2,1)])

p <- ggplot(DATAgrna, aes(x=V1,y=N,fill=V2)) +
  geom_bar(stat="identity",width=1)+
  theme_minimal()+ ylab("Count") + xlab("") + ggtitle("RNA lab, by date, by release")+
  theme(plot.title = element_text(hjust = 0.5))+theme(legend.title = element_blank())+
  theme(plot.title = element_text(hjust = 0.5,size=14,face="bold"))+
  theme(axis.text=element_text(size=11,face="bold"))+
  guides(fill = guide_legend(reverse = TRUE))+
  #  scale_y_continuous(labels=abs_comma)+theme(legend.position="none")+
  scale_x_date(breaks = as.Date(paste(2012:2020,"01-01",sep="-")),labels = date_format("%Y"))

ggplotly(p)

# rm(DATARNA1)
# rm(DATARNA2)
# rm(DATARNA)
# rm(DATAgrna)

#if (exists("DATAlab1")) {rm(DATAlab1)}
#if (exists("DATAlab2")) {rm(DATAlab2)}

```

##

```{r HIVP_DMY}

if (file.exists(file.path(filepath_old, "PAT.feather"))) {
  DATAbas1 <- data.table(read_feather(file.path(filepath_old, "PAT.feather")))
  DATAbas1[,datee:=as.Date(hivp_dmy)]
} else {
  DATAbas1 <- data.table(read_feather(file.path(filepath_old, "tblBAS.feather")))
  DATAbas1[,datee:=as.Date(hiv_pos_d)]
}  
DATAbas1[,V:=OldV]

if (file.exists(file.path(filepath_new, "PAT.feather"))) {
  # if file PAT exists (old DB structure) then read it
  DATAbas2 <- data.table(read_feather(file.path(filepath_new, "PAT.feather")))
  DATAbas2[,datee:=as.Date(hivp_dmy)]
} else {
  # if not, try to read tblBAS instead
  DATAbas2 <- data.table(read_feather(file.path(filepath_new, "tblBAS.feather")))
  DATAbas2[,datee:=as.Date(hiv_pos_d)]
}
DATAbas2[,V:=NewV]

DATAbas <- rbind(DATAbas1[,.(V,datee)],DATAbas2[,.(V,datee)],fill=TRUE)
rm(DATAgbas)
DATAgbas <- data.table(table(DATAbas$datee,DATAbas$V))
DATAgbas[,V1:=as.Date(V1)]

DATAgbas$V2 <- as.factor(DATAgbas$V2)
DATAgbas$V2 <- factor(DATAgbas$V2, levels(DATAgbas$V2)[c(2,1)])
DATAgbas[V2==OldV,N:=-N]
DATAgbas <- DATAgbas[year(V1) %between% c(2004,2020)]

p <- ggplot(DATAgbas, aes(x=V1,y=N,fill=V2)) +
  geom_bar(stat="identity",width=3)+
  theme_minimal()+ ylab("Count") + xlab("") + ggtitle("HIV test, by date, by release")+
  theme(plot.title = element_text(hjust = 0.5))+theme(legend.title = element_blank())+
  theme(plot.title = element_text(hjust = 0.5,size=14,face="bold"))+
  theme(axis.text=element_text(size=11,face="bold"))+
  guides(fill = guide_legend(reverse = TRUE)) +
  scale_x_date(breaks = as.Date(paste(seq(2004,2020,by=2),"01-01",sep="-")),labels = date_format("%Y"))

ggplotly(p)

#DATAgbas[,date_cont:=as.numeric(V1)/365.25+1970]

```

## Visits

```{r VIS}

# if file VIS exists (old DB structure) then read it
if (file.exists(file.path(filepath_old, "VIS.feather"))) {
  DATAvisit1 <- data.table(read_feather(file.path(filepath_old, "VIS.feather")))
  DATAvisit1[,VISIT_DMY:=as.Date(visit_dmy)]
  
} else {
  # if not, try to read tblVIS instead
  DATAvisit1 <- data.table(read_feather(file.path(filepath_old, "tblVIS.feather")))
  DATAvisit1[,VISIT_DMY:=as.Date(vis_d)]
}  
DATAvisit1 <- DATAvisit1[,.(VISIT_DMY)]
DATAvisit1[,V:=OldV]

# if file VIS exists (old DB structure) then read it
if (file.exists(file.path(filepath_new, "VIS.feather"))) {
  DATAvisit2 <- data.table(read_feather(file.path(filepath_new, "VIS.feather")))
  DATAvisit2[,VISIT_DMY:=as.Date(visit_dmy)]
} else {
  # if not, try to read tblVIS instead
  DATAvisit2 <- data.table(read_feather(file.path(filepath_new, "tblVIS.feather")))
  DATAvisit2[,VISIT_DMY:=as.Date(vis_d)]
}
DATAvisit2 <- DATAvisit2[,.(VISIT_DMY)]
DATAvisit2[,V:=NewV]

DATAvis <- rbind(DATAvisit1,DATAvisit2)
DATAgvis <- data.table(table(DATAvis$VISIT_DMY,DATAvis$V))

DATAgvis$V1 <- as.Date(DATAgvis$V1)

DATAgvis[V2==OldV,N:=-N]

DATAgvis <- DATAgvis[!which(year(V1)<2012)]
DATAgvis <- DATAgvis[!which(year(V1)>2020)]

DATAgvis$V2 <- as.factor(DATAgvis$V2)
DATAgvis$V2 <- factor(DATAgvis$V2, levels(DATAgvis$V2)[c(2,1)])

p <- ggplot(DATAgvis, aes(x=V1,y=N,fill=V2)) +
  geom_bar(stat="identity",width=1)+
  theme_minimal()+ ylab("Count") + xlab("") + ggtitle("Visit, by date, by release")+
  #theme(plot.title = element_text(hjust = 0.5))+theme(legend.title = element_blank())+
  theme(plot.title = element_text(hjust = 0.5,size=14,face="bold"))+
  theme(axis.text=element_text(size=11,face="bold"))+
  guides(fill = guide_legend(reverse = TRUE))+
#  scale_y_continuous(labels=abs_comma)+theme(legend.position="none")+
  scale_x_date(breaks = as.Date(paste(2012:2020,"01-01",sep="-")),labels = date_format("%Y"))

ggplotly(p)

rm(DATAvisit1)
rm(DATAvisit2)
rm(DATAvis)
rm(DATAgvis)
```

```{r PAT}

if ("frsvis_dmy" %in% colnames(DATAbas1)) {
  DATAbas1[,year:=year(frsvis_dmy)]
} else {
  DATAbas1[,year:=year(enrol_d)]
}

if ("frsvis_dmy" %in% colnames(DATAbas2)) {
  DATAbas2[,year:=year(frsvis_dmy)]
} else {
  DATAbas2[,year:=year(enrol_d)]
}

DATAbas <- rbind(DATAbas1[,.(year,V)],DATAbas2[,.(year,V)],fill=TRUE)

DATAgbas <- data.table(table(DATAbas$year,DATAbas$V))

DATAgbas$V2 <- as.factor(DATAgbas$V2)
DATAgbas$V2 <- factor(DATAgbas$V2, levels(DATAgbas$V2)[c(2,1)])
DATAgbas <- DATAgbas[V1 %between% c(2004,2020),]

# Plot enrolment date / 1st visit
ggplot(DATAgbas, aes(x=V1, y=N, fill=V2)) +
  geom_bar(stat="identity", color="black", position=position_dodge(),width = .7)+
  theme_minimal()+   ylab("Count") + xlab("") + ggtitle("First visit / enrolment date")+
  theme(plot.title = element_text(hjust = 0.5,size=14,face="bold"))+theme(legend.title = element_blank())+
  theme(legend.position="bottom")

```

## ART

```{r ART}
# Get HAART date from PAT/tblBAS data table
if ("haart_dmy" %in% colnames(DATAbas1)) {
  DATAbas1[,datee:=as.Date(haart_dmy)]
} else {
  DATAbas1[,datee:=as.Date(recart_d)]
}  
DATAbas1[,V:=OldV]

if ("haart_dmy" %in% colnames(DATAbas2)) {
  DATAbas2[,datee:=as.Date(haart_dmy)]
} else {
  DATAbas2[,datee:=as.Date(recart_d)]
}  
DATAbas2[,V:=NewV]

DATAbas <- rbind(DATAbas1[,.(V,datee)],DATAbas2[,.(V,datee)],fill=TRUE)

DATAgbas <- data.table(table(DATAbas$datee,DATAbas$V))
DATAgbas[,V1:=as.Date(V1)]

DATAgbas$V2=as.factor(DATAgbas$V2)
DATAgbas$V2 <- factor(DATAgbas$V2, levels(DATAgbas$V2)[c(2,1)])
DATAgbas[V2==OldV,N:=-N]
DATAgbas <- DATAgbas[year(V1)>=2000]
DATAgbas <- DATAgbas[year(V1) %between% c(2004,2020),]

#
p <- ggplot(DATAgbas, aes(x=V1,y=N,fill=V2)) +
  geom_bar(stat="identity",width=3)+
  theme_minimal()+ ylab("Count") + xlab("") + ggtitle("Starting ART, by date, by release")+
  theme(plot.title = element_text(hjust = 0.5))+theme(legend.title = element_blank())+
  theme(plot.title = element_text(hjust = 0.5,size=14,face="bold"))+
  theme(axis.text=element_text(size=11,face="bold"))+
  guides(fill = guide_legend(reverse = TRUE))+
  #  scale_y_continuous(labels=abs_comma)+theme(legend.position="none")+
  scale_x_date(breaks =as.Date(paste(seq(2004,2020,by=2),"01-01",sep="-")),labels = date_format("%Y"))

ggplotly(p)

```

```{r}
# Moved up
# if ("hivp_dmy" %in% colnames(DATAbas1)) {
#   DATAbas1[,datee:=as.Date(hivp_dmy)]
# } else {
#   DATAbas1[,datee:=as.Date(hiv_pos_d)]
# }  
# 
# if ("hivp_dmy" %in% colnames(DATAbas2)) {
#   DATAbas2[,datee:=as.Date(hivp_dmy)]
# } else {
#   DATAbas2[,datee:=as.Date(hiv_pos_d)]
# }
# 
# DATAbas <- rbind(DATAbas1[,.(V,datee)],DATAbas2[,.(V,datee)],fill=TRUE)
# rm(DATAgbas)
# DATAgbas <- data.table(table(DATAbas$datee,DATAbas$V))
# DATAgbas[,V1:=as.Date(V1)]
# 
# DATAgbas$V2 <- as.factor(DATAgbas$V2)
# DATAgbas$V2 <- factor(DATAgbas$V2, levels(DATAgbas$V2)[c(2,1)])
# DATAgbas[V2==OldV,N:=-N]
# DATAgbas <- DATAgbas[year(V1) %between% c(2004,2020)]
# 
# ggplot(DATAgbas, aes(x=V1,y=N,fill=V2)) +
#   geom_bar(stat="identity",width=10)+
#   theme_minimal()+ ylab("Count") + xlab("Year") + ggtitle("HIV test, by date, by release")+
#   theme(plot.title = element_text(hjust = 0.5))+theme(legend.title = element_blank())+
#   theme(plot.title = element_text(hjust = 0.5,size=14,face="bold"))+
#   theme(axis.text=element_text(size=11,face="bold"))+
#   guides(fill = guide_legend(reverse = TRUE)) +
#   scale_x_date(breaks = as.Date(paste(seq(2004,2020,by=2),"01-01",sep="-")),labels = date_format("%Y"))
#   
# #DATAgbas[,date_cont:=as.numeric(V1)/365.25+1970]

```

## Outcomes

```{r OUTCOME}

# DATAbas1 var already created, check if it contains "outcome_dmy) (table PAT) 
if ("outcome_dmy" %in% colnames(DATAbas1)) {
  DATAbas1[,outcome:=as.numeric(gsub("([0-9]+).*$", "\\1", outcome))]
  # view outcome values
  # unique(DATAbas1$outcome)
  
  # Create outcome labels "dead", "Transfer", "RIC" and "LTFU"
  DATAbas1[outcome %between% c(10,12),outcomef:="dead"]
  DATAbas1[outcome ==20,outcomef:="RIC"]
  DATAbas1[outcome %in% c(21, 30,31),outcomef:="Transfer"]
  DATAbas1[outcome %in% c(40,41,22,23),outcomef:="LTFU"]
  
} else {
  # if not, read tblLTFU
  DATAbas1 <- data.table(read_feather(file.path(filepath_old, "tblLTFU.feather")))
  # Create outcome labels "dead", "Transfer" and "LTFU"
  DATAbas1[death_y==1,outcomef:="dead"]
  DATAbas1[drop_y==1 & drop_rs%in% c(4,4.1),outcomef:="Transfer"]
  DATAbas1[drop_y==1 & is.na(outcomef),outcomef:="LTFU"]
}  

if ("outcome_dmy" %in% colnames(DATAbas2)) {
  # view outcome values
  # unique(DATAbas2$outcome)
  DATAbas2[,outcome:=as.numeric(gsub("([0-9]+).*$", "\\1", outcome))]
  
  # Create outcome labels "dead", "Transfer", "RIC" and "LTFU"
  DATAbas2[outcome %between% c(10,12),outcomef:="dead"]
  DATAbas2[outcome ==20,outcomef:="RIC"]
  DATAbas2[outcome %in% c(21, 30,31),outcomef:="Transfer"]
  DATAbas2[outcome %in% c(40,41,22,23),outcomef:="LTFU"]
} else {
  # read tblLTFU
  DATAbas2 <- data.table(read_feather(file.path(filepath_new, "tblLTFU.feather")))
  
  # Create outcome labels "dead", "Transfer" and "LTFU"
  DATAbas2[death_y==1,outcomef:="dead"]
  DATAbas2[drop_y==1 & drop_rs%in% c(4,4.1),outcomef:="Transfer"]
  DATAbas2[drop_y==1 & is.na(outcomef),outcomef:="LTFU"]
} 

print("outcomes (Old):")
prop.table(table(DATAbas1$outcomef,useNA="always"))
#NA = retained in care ?
print("outcomes (New):")
prop.table(table(DATAbas2$outcomef,useNA="always"))

DATAbas1[,V:=OldV]
DATAbas2[,V:=NewV]
DATAbas <- rbind(DATAbas1[,.(outcomef,V)],DATAbas2[,.(outcomef,V)])
DATAgbas <- data.table(prop.table(table(DATAbas$outcomef,DATAbas$V,useNA="always"),margin=2))
#DATAgbas has empty too
DATAgbas <- DATAgbas[!is.na(V2),] # ????

DATAgbas$V2 <- factor(DATAgbas$V2,levels=c(OldV,NewV))

DATAgbas$V1 <- factor(DATAgbas$V1, levels = c("dead","LTFU","Transfer","RIC",NA))

# Plot outcome distribution
ggplot(DATAgbas, aes(x=V2, y=N, fill=V1)) +
  geom_bar(stat="identity", color="black")+ylab("Proportion") + 
  scale_fill_manual(values=c("red4","blue4","chartreuse4","orange","white"))+
  theme(axis.title.x=element_blank(),
        axis.ticks.x=element_blank())+theme(legend.title = element_blank())+ 
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5,size=14,face="bold"))+
  theme(legend.title = element_blank())+ 
  ggtitle("Outcome distribution")

rm(DATAbas)
rm(DATAgbas)

```

```{r Death}

# CHDAO 22.01.2021 both DATAbas1 (Old) and DATAbas2 (New) already exist, build DATAdeath* based on DATAbas*
DATAdeath1 <- copy(DATAbas1)
DATAdeath2 <- copy(DATAbas2)

# only check which DB structure
if ("outcome_dmy" %in% colnames(DATAdeath1)) {
  DATAdeath1[,datee:=as.Date(outcome_dmy)]
  # add new column "dead = 1" when outcome in (10, 11, 12)
  DATAdeath1[outcome %between% c(10,12),dead:=1]
} else {
  # add new column "dead = 1" when death_y = 1
  DATAdeath1[death_y==1,dead:=1]
  DATAdeath1[,datee:=as.Date(death_d)]
}  

# Test count dead #DATAdeath1[, .(count = .N),by = dead]
if ("outcome_dmy" %in% colnames(DATAdeath2)) {
  DATAdeath2[,datee:=as.Date(outcome_dmy)]
  # add new column "dead = 1" when outcome in (10, 11, 12)
  DATAdeath2[outcome %between% c(10,12),dead:=1]
} else {
  # add new column "dead = 1" when death_y = 1
  DATAdeath2[death_y==1,dead:=1]
  DATAdeath2[,datee:=as.Date(death_d)]
}   

# Keep only death patients
DATAdeath1=DATAdeath1[dead==1,]
DATAdeath2=DATAdeath2[dead==1,]

# CHDAO ???? What is the difference ?
# DATAdeath <- rbind(DATAdeath1[,.(datee,V)],DATAdeath2[,.(datee,V)],fill=TRUE)
DATAdeath <- rbind(DATAdeath1,DATAdeath2,fill=TRUE)

DATAgdeath <- data.table(table(DATAdeath$datee,DATAdeath$V))
DATAgdeath[,V1:=as.Date(V1)]

DATAgdeath$V2 <- as.factor(DATAgdeath$V2)
DATAgdeath$V2 <- factor(DATAgdeath$V2, levels(DATAgdeath$V2)[c(2,1)])
DATAgdeath[V2==OldV,N:=-N]
# DROPPED # DATAgdeath=DATAgdeath[year(V1) %between% c(2008,2020)]
DATAgdeath=DATAgdeath[year(V1)>=2008]

# Plot Death by date
p <- ggplot(DATAgdeath, aes(x=V1,y=N,fill=V2)) +
  geom_bar(stat="identity",width=3)+
  theme_minimal()+ ylab("Count") + xlab("") + ggtitle("Death by date")+
  theme(plot.title = element_text(hjust = 0.5))+theme(legend.title = element_blank())+
  theme(plot.title = element_text(hjust = 0.5,size=14,face="bold"))+
  theme(axis.text=element_text(size=11,face="bold"))+
  guides(fill = guide_legend(reverse = TRUE))+
  #  scale_y_continuous(labels=abs_comma)+theme(legend.position="none")+
  scale_x_date(breaks = as.Date(paste(seq(2008,2020,by=2),"01-01",sep="-")),labels = date_format("%Y"))

ggplotly(p)

# Prepare data for Death by year
DATAgdeath <- data.table(table(year(DATAdeath$datee),DATAdeath$V))
DATAgdeath$V2 <- as.factor(DATAgdeath$V2)
DATAgdeath$V2 <- factor(DATAgdeath$V2, levels(DATAgdeath$V2)[c(2,1)])

# Plot Death by year
ggplot(DATAgdeath, aes(x=V1, y=N, fill=V2)) +
  geom_bar(stat="identity", color="black", position=position_dodge(),width = .7)+
  theme_minimal()+   ylab("Count") + xlab("") + ggtitle("Death by year")+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(plot.title = element_text(hjust = 0.5,size=14,face="bold")) +
  theme(legend.title = element_blank())

# Plot done, remove variables
rm(DATAdeath1)
rm(DATAdeath2)
rm(DATAdeath)
rm(DATAgdeath)

```

```{r Transfer}
# Extract "transfer" patients from DATAbas*
DATAtransfer1 <- DATAbas1[outcomef=="Transfer"]
DATAtransfer2 <- DATAbas2[outcomef=="Transfer"]

if ("outcome_dmy" %in% colnames(DATAtransfer1)) {
  DATAtransfer1[,datee:=as.Date(outcome_dmy)]
} else {
  DATAtransfer1[,datee:=as.Date(drop_d)]
}  

if ("outcome_dmy" %in% colnames(DATAtransfer2)) {
  DATAtransfer2[,datee:=as.Date(outcome_dmy)]
} else {
  DATAtransfer2[,datee:=as.Date(drop_d)]
} 

# Keep only 2 cols "dateee" and "V"
DATAtransfer <- rbind(DATAtransfer1[,.(datee,V)],DATAtransfer2[,.(datee,V)],fill=TRUE)
#DATAtransfer <- rbind(DATAtransfer1,DATAtransfer2,fill=TRUE)

DATAgtransfer <- data.table(table(DATAtransfer$datee,DATAtransfer$V))
DATAgtransfer[,V1:=as.Date(V1)]

DATAgtransfer$V2 <- as.factor(DATAgtransfer$V2)
DATAgtransfer$V2 <- factor(DATAgtransfer$V2, levels(DATAgtransfer$V2)[c(2,1)])
DATAgtransfer[V2==OldV,N:=-N]
DATAgtransfer=DATAgtransfer[year(V1)>=2004]

p <- ggplot(DATAgtransfer, aes(x=V1,y=N,fill=V2)) +
  geom_bar(stat="identity",width=3)+
  theme_minimal()+ ylab("Count") + xlab("") + ggtitle("Transfer by date")+
  theme(plot.title = element_text(hjust = 0.5))+theme(legend.title = element_blank())+
  theme(plot.title = element_text(hjust = 0.5,size=14,face="bold"))+
  theme(axis.text=element_text(size=11,face="bold"))+
  guides(fill = guide_legend(reverse = TRUE))+
  #  scale_y_continuous(labels=abs_comma)+theme(legend.position="none")+
  scale_x_date(breaks = as.Date(paste(seq(2004,2020,by=2),"01-01",sep="-")),labels = date_format("%Y"))

ggplotly(p)

rm(DATAtransfer1)
rm(DATAtransfer2)
rm(DATAtransfer)
rm(DATAgtransfer)

```

## Missingness

```{r MISSING (tblBAS)}

if ("birth_dmy" %in% colnames(DATAbas1)) {
  DATANA1 <- DATAbas1[,.(birth_dmy=as.Date(birth_dmy),exp_y,gender,haart_dmy=as.Date(haart_dmy),hivp_dmy=as.Date(hivp_dmy)), V]
} else {
  DATAbas1 <- data.table(read_feather(file.path(filepath_old, "tblBAS.feather")))
  DATANA1 <- DATAbas1[,.(birth_dmy=as.Date(birth_d),exp_y=naive_y,gender=sex,haart_dmy=as.Date(recart_d),hivp_dmy=as.Date(hiv_pos_d))]
  DATANA1[,V:=OldV]
}

if ("birth_dmy" %in% colnames(DATAbas2)) {
  DATANA2 <- DATAbas2[,.(birth_dmy=as.Date(birth_dmy),exp_y,gender,haart_dmy=as.Date(haart_dmy),hivp_dmy=as.Date(hivp_dmy)), V]
} else {
  DATAbas2 <- data.table(read_feather(file.path(filepath_new, "tblBAS.feather")))
  DATANA2 <- DATAbas2[,.(birth_dmy=as.Date(birth_d),exp_y=naive_y,gender=sex,haart_dmy=as.Date(recart_d),hivp_dmy=as.Date(hiv_pos_d))]
  DATANA2[,V:=NewV]
}

DATANA3 <- rbind(DATANA1,DATANA2)
DATANA3[exp_y>2,exp_y:=NA]

DATANA <- data.table(matrix("Exist",nrow=nrow(DATANA3),ncol=ncol(DATANA3)))
DATANA[is.na(DATANA3)] <- "IAMNA"
colnames(DATANA) <- colnames(DATANA3)
DATANA[,V:=DATANA3$V]
# colnames(DATANA)
# foreach(tab=colnames(DATANA)) %do% {
#   DATANAg <- data.table(prop.table(table(as.vector(DATANA[,get(tab)]),DATANA$V),margin=2))[V1=="IAMNA",]
#   if(nrow(DATANAg)==2){#This condition allows to not produce error if there is 0 missing value
#     DATANAg$V2 <- as.factor(DATANAg$V2)
#     DATANAg$V2 <- factor(DATANAg$V2, levels(DATANAg$V2)[c(2,1)])
#     #add ylim 0,1 AND prop on top of the graph
#     #Assign to tab_graph
#     assign(paste0(tab,"_graph") , 
#            ggplot(DATANAg, aes(x=V1, y=N, fill=V2)) +
#              geom_bar(stat="identity", color="black", position=position_dodge(),width = .7)+
#              theme_minimal()+   ylab("Percentage") + xlab("Year") + ggtitle(paste(tab,"missing"))+
#              theme(plot.title = element_text(hjust = 0.5))+theme(legend.title = element_blank())+
#              ylim(0,1) + theme(plot.title = element_text(hjust = 0.5,size=10,face="bold"))+
#              geom_text(aes(x=V1,label=paste0(round(N,4)*100,"%")), position=position_dodge(width=0.7), vjust=-0.25)+
#              theme(axis.title.x=element_blank(),
#                    axis.text.x=element_blank(),
#                    axis.ticks.x=element_blank()),
#            envir=.GlobalEnv
#     )
#   } else  
# {assign(paste0(tab,"_graph"), ggplot()+theme_minimal())}
#   
# }
# CHDAO 22.01.2021 Yann modified to remove empty plot
print(paste("Assessing missingness in the following variables:",paste(setdiff(colnames(DATANA),"V"),collapse=", ")))
for(tab in setdiff(colnames(DATANA),"V")){
  DATANAg <- data.table(prop.table(table(as.vector(DATANA[,get(tab)]),DATANA$V),margin=2))[V1=="IAMNA",]
  if(nrow(DATANAg)==2)
    {#This condition allows to not produce error if there is 0 missing value
    DATANAg$V2 <- as.factor(DATANAg$V2)
    DATANAg$V2 <- factor(DATANAg$V2, levels(DATANAg$V2)[c(2,1)])
    #add ylim 0,1 AND prop on top of the gra
    print(ggplot(DATANAg, aes(x=V1, y=N, fill=V2)) +
             geom_bar(stat="identity", color="black", position=position_dodge(),width = .7)+
             theme_minimal()+   ylab("Percentage") + xlab("Year") + ggtitle(paste("\n\n",tab," missing",sep=''))+
             theme(plot.title = element_text(hjust = 0.5))+theme(legend.title = element_blank())+
             ylim(0,1) + theme(plot.title = element_text(hjust = 0.5,size=10,face="bold"))+
             geom_text(aes(x=V1,label=paste0(round(N,4)*100,"%")), position=position_dodge(width=0.7), vjust=-0.25)+
             theme(axis.title.x=element_blank(),
                   axis.text.x=element_blank(),
                   axis.ticks.x=element_blank()))
  } 
}
rm(DATAbas1)
rm(DATAbas2)

rm(DATANA1)
rm(DATANA2)
rm(DATANA3)
rm(DATANA)
rm(DATANAg)

```

```{r missing (tblVIS)}

# if file VIS exists (old DB structure) then read it
if (file.exists(file.path(filepath_old, "VIS.feather"))) {
  DATAvisit1 <- data.table(read_feather(file.path(filepath_old, "VIS.feather")))
  
} else {
  # if not, try to read tblVIS instead
  DATAvisit1 <- data.table(read_feather(file.path(filepath_old, "tblVIS.feather")))
}
if("next_visit_d" %in% colnames(DATAvisit1))
{
  DATAvisit1 <- DATAvisit1[,.(next_visit_dmy=as.Date(next_visit_d))]
} else if("next_visit_dmy" %in% colnames(DATAvisit1)){
  DATAvisit1 <- DATAvisit1[,.(next_visit_dmy=as.Date(next_visit_dmy))]
}
DATAvisit1[,V:=OldV]


# if file VIS exists (old DB structure) then read it
if (file.exists(file.path(filepath_new, "VIS.feather"))) {
  DATAvisit2 <- data.table(read_feather(file.path(filepath_new, "VIS.feather")))
} else {
  # if not, try to read tblVIS instead
  DATAvisit2 <- data.table(read_feather(file.path(filepath_new, "tblVIS.feather")))
}
if("next_visit_d" %in% colnames(DATAvisit2))
{
  DATAvisit2 <- DATAvisit2[,.(next_visit_dmy=as.Date(next_visit_d))]
} else if("next_visit_dmy" %in% colnames(DATAvisit2)){
  DATAvisit2 <- DATAvisit2[,.(next_visit_dmy=as.Date(next_visit_dmy))]
}
DATAvisit2[,V:=NewV]

DATAvis <- rbind(DATAvisit1,DATAvisit2)

DATANA <- data.table(matrix("Exist",nrow=nrow(DATAvis),ncol=ncol(DATAvis)))
DATANA[is.na(DATAvis)] <- "IAMNA"
colnames(DATANA) <- colnames(DATAvis)
DATANA[,V:=DATAvis$V]

# CHDAO 22.01.2021 Yann modified to remove empty plot
print(paste("Assessing missingness in the following variables:",paste(setdiff(colnames(DATANA),"V"),collapse=", ")))
for(tab in setdiff(colnames(DATANA),"V")){
  DATANAg <- data.table(prop.table(table(as.vector(DATANA[,get(tab)]),DATANA$V),margin=2))[V1=="IAMNA",]
  if(nrow(DATANAg)==2)
    {#This condition allows to not produce error if there is 0 missing value
    DATANAg$V2 <- as.factor(DATANAg$V2)
    DATANAg$V2 <- factor(DATANAg$V2, levels(DATANAg$V2)[c(2,1)])
    #add ylim 0,1 AND prop on top of the gra
    print(ggplot(DATANAg, aes(x=V1, y=N, fill=V2)) +
             geom_bar(stat="identity", color="black", position=position_dodge(),width = .7)+
             theme_minimal()+   ylab("Percentage") + xlab("Year") + ggtitle(paste("\n\n",tab," missing",sep=''))+
             theme(plot.title = element_text(hjust = 0.5))+theme(legend.title = element_blank())+
             ylim(0,1) + theme(plot.title = element_text(hjust = 0.5,size=10,face="bold"))+
             geom_text(aes(x=V1,label=paste0(round(N,4)*100,"%")), position=position_dodge(width=0.7), vjust=-0.25)+
             theme(axis.title.x=element_blank(),
                   axis.text.x=element_blank(),
                   axis.ticks.x=element_blank()))
  } 
}

```

## ART regimes

```{r ART regimes}

if(file.exists(file.path(filepath_old, "ART.feather"))) {
  DATAart1 <- data.table(read_feather(file.path(filepath_old, "ART.feather")))
} else {
  DATAart1 <- data.table(read_feather(file.path(filepath_old, "tblART.feather")))
}  
  
if(file.exists(file.path(filepath_new, "ART.feather"))) {
  DATAart2 <- data.table(read_feather(file.path(filepath_new, "ART.feather")))
} else {
  DATAart2 <- data.table(read_feather(file.path(filepath_new, "tblART.feather")))
}                        

if("art_sd_dmy" %in% colnames(DATAart1))
  setnames(DATAart1,"art_sd_dmy","art_sd")
if("art_sd_dmy" %in% colnames(DATAart2))
  setnames(DATAart2,"art_sd_dmy","art_sd")
  

DATAart1[,V:=OldV]
DATAart2[,V:=NewV]

DATAart <- rbind(DATAart1[,.(art_id,year=year(art_sd),V)],DATAart2[,.(art_id,year=year(art_sd),V)])

# the four/ten most common drugs across both datasets
art <- DATAart[,sort(table(art_id),decreasing=TRUE)]
art_4mc <- names(art)[1:4]
art_10mc <- names(art)[1:10]

graph_list <- NULL

for(tab in art_4mc)  # looping over four most common drugs
{
  DATAgart <- DATAart[art_id==tab]
  DATAgart <- data.table(table(DATAgart$year,DATAgart$V))
  DATAgart[,V2:=as.factor(V2)]
  DATAgart[,V2:=factor(V2,levels=c(OldV,NewV))]
 
  DATAgart <- DATAgart[V1 %between% c(2004,2020)]

  print(ggplot(DATAgart, aes(x=V1, y=N, fill=V2)) +
    geom_bar(stat="identity", color="black", position=position_dodge(),width = .7)+
    theme_minimal()+   ylab("Count") + xlab("Year") + ggtitle(paste("Number of records, drug",tab))+
    theme(plot.title = element_text(hjust = 0.5))+theme(legend.title = element_blank())+
    theme(legend.position="bottom"))
  rm(DATAgart)
}

DATAgart <- DATAart[art_id%in%art_10mc]
DATAgart <- data.table(prop.table(table(DATAgart$art_id,DATAgart$V),margin=2))
DATAgart[,V2:=factor(V2,levels=c(OldV,NewV))]

ggplot(DATAgart, aes(x=V2, y=N, fill=V1)) +
  geom_bar(stat="identity", color="black")+ylab("Proportion") + xlab("") +
  theme(axis.title.x=element_blank(),axis.ticks.x=element_blank())+
  theme(legend.title = element_blank())+
  ggtitle("Drug distribution (10 most common)")+theme_minimal() +
  labs(fill="Drug")

```